[package]
name = "zero2prod"
version = "0.1.0"
authors = ["June Park <jnepark202012@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = { version = "4.9.0" }
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = "0.12.5"

[dependencies.sqlx]
version = "0.8.0"
default-features = false
features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate"]